
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    networks:
      - node-project
    expose:
      - 4000

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8070:8070"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
    networks:
      - node-project

networks:
  node-project:
    driver: bridge