name: CI setup for Nodejs API app

on:
  workflow_dispatch:

permissions:
  contents: write
  # Add other permissions as needed, but do not use write-all


jobs:
  Linting:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: Apurva14A/deploy-api-nginx-prod/.github/workflows/dependencies.yml@main

      # - name: Install and configure eslint
      #   run: |
      #     npm install --save-dev eslint

      - name: Run linting
        run: |
          npm run lint 


  Code_coverage:
    runs-on: [ubuntu-latest]
    needs: Linting
    

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      # Checkout Code repository
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      # Setup nodejs environement

      - name: Install dependencies
        uses: Apurva14A/deploy-api-nginx-prod/.github/workflows/dependencies.yml@main

      - name: Code Coverage by SonarQube
        run: |
          npm install -g @sonar/scan
          sonar-scanner -Dsonar.organization=apurva14a -Dsonar.projectKey=Apurva14A_deploy-api-nginx-prod  -Dsonar.sources=node-api-project -Dsonar.token=${{ env.SONAR_TOKEN }} 
        